--- 
abstract: "Format DateTime For RSS "
author: Copyright (c) 2006 Daisuke Maki <gdmaki@cpan.org>, Tatsuhiko Miyagawa <miyagawa@bulknews.net>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Format-RSS
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime::Format::DateParse: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::Mail: 0
version: 0.02
